# Generated by Django 5.2.15 on 2026-07-14 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('complexes', '0001_initial'),
        ('providers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('awaiting_assignment', 'Awaiting assignment'), ('assigned', 'Assigned to provider'), ('accepted', 'Accepted by provider'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='new', max_length=32)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=16)),
                ('source', models.CharField(choices=[('direct', 'Direct from resident'), ('ai', 'AI processed'), ('import', 'Imported'), ('integration', 'External integration')], default='direct', max_length=16)),
                ('external_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='providers.servicecategory')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_tickets', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='providers.provider')),
                ('residential_complex', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='complexes.residentialcomplex')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='TicketStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(choices=[('new', 'New'), ('awaiting_assignment', 'Awaiting assignment'), ('assigned', 'Assigned to provider'), ('accepted', 'Accepted by provider'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=32)),
                ('to_status', models.CharField(choices=[('new', 'New'), ('awaiting_assignment', 'Awaiting assignment'), ('assigned', 'Assigned to provider'), ('accepted', 'Accepted by provider'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=32)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_status_changes', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='tickets.ticket')),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['residential_complex', 'status'], name='tickets_tic_residen_0d9280_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['provider', 'status'], name='tickets_tic_provide_e52035_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['assignee', 'status'], name='tickets_tic_assigne_294cb9_idx'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id__isnull', False)), fields=('residential_complex', 'source', 'external_id'), name='unique_external_ticket_per_complex_source'),
        ),
        migrations.AddConstraint(
            model_name='ticketstatushistory',
            constraint=models.CheckConstraint(condition=models.Q(('from_status', models.F('to_status')), _negated=True), name='ticket_history_statuses_must_differ'),
        ),
    ]
