# Generated by Django 5.2.15 on 2026-07-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('low', 'Низкий'), ('normal', 'Обычный'), ('high', 'Высокий'), ('urgent', 'Срочный')], default='normal', max_length=16),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='source',
            field=models.CharField(choices=[('direct', 'От жителя'), ('ai', 'Обработана ИИ'), ('import', 'Импортирована'), ('integration', 'Внешняя интеграция')], default='direct', max_length=16),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('awaiting_assignment', 'Ожидает назначения'), ('assigned', 'Назначена поставщику'), ('accepted', 'Принята поставщиком'), ('in_progress', 'В работе'), ('completed', 'Выполнена'), ('cancelled', 'Отменена')], default='new', max_length=32),
        ),
        migrations.AlterField(
            model_name='ticketstatushistory',
            name='from_status',
            field=models.CharField(choices=[('new', 'Новая'), ('awaiting_assignment', 'Ожидает назначения'), ('assigned', 'Назначена поставщику'), ('accepted', 'Принята поставщиком'), ('in_progress', 'В работе'), ('completed', 'Выполнена'), ('cancelled', 'Отменена')], max_length=32),
        ),
        migrations.AlterField(
            model_name='ticketstatushistory',
            name='to_status',
            field=models.CharField(choices=[('new', 'Новая'), ('awaiting_assignment', 'Ожидает назначения'), ('assigned', 'Назначена поставщику'), ('accepted', 'Принята поставщиком'), ('in_progress', 'В работе'), ('completed', 'Выполнена'), ('cancelled', 'Отменена')], max_length=32),
        ),
    ]
