# Generated by Django 5.2.15 on 2026-07-17 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complexes', '0003_alter_residentialcomplexmembership_role_and_more'),
        ('tickets', '0002_alter_ticket_priority_alter_ticket_source_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('apartment', models.CharField(blank=True, max_length=32)),
                ('external_id', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('residential_complex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='complexes.residentialcomplex')),
            ],
            options={
                'ordering': ('full_name', 'apartment'),
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='applicant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='tickets.applicant'),
        ),
        migrations.AddConstraint(
            model_name='applicant',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id__isnull', False)), fields=('residential_complex', 'external_id'), name='unique_applicant_external_id_per_complex'),
        ),
    ]
