# Generated by Django 5.2.15 on 2026-07-17 14:46

from django.db import migrations


def migrate_applicants(apps, schema_editor):
    Ticket = apps.get_model('tickets', 'Ticket')
    Applicant = apps.get_model('tickets', 'Applicant')
    User = apps.get_model('users', 'User')
    Membership = apps.get_model('complexes', 'ResidentialComplexMembership')

    pairs = Ticket.objects.values_list(
        'residential_complex_id',
        'customer_id',
    ).distinct()
    users = User.objects.in_bulk({customer_id for _, customer_id in pairs})

    for residential_complex_id, customer_id in pairs:
        user = users[customer_id]
        full_name = ' '.join(
            part for part in (user.first_name, user.last_name) if part
        ).strip() or user.username
        applicant, _ = Applicant.objects.get_or_create(
            residential_complex_id=residential_complex_id,
            external_id=f'legacy-user-{customer_id}',
            defaults={
                'full_name': full_name,
                'email': user.email,
            },
        )
        Ticket.objects.filter(
            residential_complex_id=residential_complex_id,
            customer_id=customer_id,
        ).update(applicant_id=applicant.pk)

    # Роль жителя больше не является ролью доступа к служебной системе.
    Membership.objects.filter(role='resident').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_applicant_ticket_applicant_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_applicants, migrations.RunPython.noop),
    ]
