# Generated by Django 5.2.15 on 2026-07-14 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('providers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResidentialComplex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=270, unique=True)),
                ('address', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'residential complex',
                'verbose_name_plural': 'residential complexes',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ResidentialComplexProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('platform', 'Platform catalog'), ('complex', 'Residential complex')], max_length=20)),
                ('is_preferred', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residential_complex_links', to='providers.provider')),
                ('residential_complex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_links', to='complexes.residentialcomplex')),
                ('service_categories', models.ManyToManyField(blank=True, related_name='residential_complex_provider_links', to='providers.servicecategory')),
            ],
            options={
                'ordering': ('residential_complex__name', 'provider__name'),
            },
        ),
        migrations.AddField(
            model_name='residentialcomplex',
            name='providers',
            field=models.ManyToManyField(blank=True, related_name='residential_complexes', through='complexes.ResidentialComplexProvider', to='providers.provider'),
        ),
        migrations.CreateModel(
            name='ResidentialComplexMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('resident', 'Resident'), ('dispatcher', 'Dispatcher'), ('manager', 'Manager')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('residential_complex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='complexes.residentialcomplex')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residential_complex_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('residential_complex__name', 'user__username'),
                'constraints': [models.UniqueConstraint(fields=('user', 'residential_complex'), name='unique_complex_membership')],
            },
        ),
        migrations.AddConstraint(
            model_name='residentialcomplexprovider',
            constraint=models.UniqueConstraint(fields=('residential_complex', 'provider'), name='unique_complex_provider'),
        ),
    ]
