# Generated by Django 5.2.15 on 2026-07-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complexes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residentialcomplexmembership',
            name='role',
            field=models.CharField(choices=[('resident', 'Житель'), ('dispatcher', 'Диспетчер'), ('manager', 'Руководитель ЖК')], max_length=20),
        ),
        migrations.AlterField(
            model_name='residentialcomplexprovider',
            name='source',
            field=models.CharField(choices=[('platform', 'Каталог платформы'), ('complex', 'Добавлен жилым комплексом')], max_length=20),
        ),
    ]
