# Generated by Django 5.2.15 on 2026-07-17 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complexes', '0002_alter_residentialcomplexmembership_role_and_more'),
        ('providers', '0002_alter_providermembership_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residentialcomplexmembership',
            name='role',
            field=models.CharField(choices=[('dispatcher', 'Диспетчер'), ('manager', 'Руководитель ЖК')], max_length=20),
        ),
        migrations.CreateModel(
            name='ServiceRoutingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('manual', 'Через диспетчера ТСЖ'), ('direct', 'Сразу поставщику')], default='manual', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routing_rules', to='providers.servicecategory')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='direct_routing_rules', to='providers.provider')),
                ('residential_complex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routing_rules', to='complexes.residentialcomplex')),
            ],
            options={
                'ordering': ('residential_complex__name', 'category__name'),
                'constraints': [models.UniqueConstraint(fields=('residential_complex', 'category'), name='unique_routing_rule_per_complex_category')],
            },
        ),
    ]
