# Generated by Django 5.2.15 on 2026-07-20 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complexes', '0003_alter_residentialcomplexmembership_role_and_more'),
        ('providers', '0002_alter_providermembership_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='residentialcomplex',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='residentialcomplex',
            name='contact_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='residentialcomplex',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='residentialcomplex',
            name='launched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='residentialcomplex',
            name='lifecycle_status',
            field=models.CharField(choices=[('setup', 'Настраивается'), ('active', 'Работает'), ('suspended', 'Приостановлен')], default='setup', max_length=16),
        ),
        migrations.AddField(
            model_name='residentialcomplex',
            name='management_company',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='residentialcomplex',
            name='timezone',
            field=models.CharField(default='Asia/Yekaterinburg', max_length=64),
        ),
        migrations.AddField(
            model_name='residentialcomplexprovider',
            name='auto_assignment_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='residentialcomplexprovider',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='residentialcomplexprovider',
            name='contact_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='residentialcomplexprovider',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='residentialcomplexprovider',
            name='contract_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='residentialcomplexprovider',
            name='contract_valid_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ComplexConfigurationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('profile', 'Данные ЖК'), ('team', 'Команда'), ('channel', 'Канал заявок'), ('service', 'Услуга'), ('provider', 'Поставщик'), ('routing', 'Маршрутизация'), ('test', 'Тестовый запуск'), ('launch', 'Запуск ЖК')], max_length=20)),
                ('description', models.CharField(max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complex_configuration_events', to=settings.AUTH_USER_MODEL)),
                ('residential_complex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuration_events', to='complexes.residentialcomplex')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ImplementationTestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_successful', models.BooleanField(default=False)),
                ('results', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('residential_complex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='implementation_test_runs', to='complexes.residentialcomplex')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='implementation_test_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ResidentialComplexIntakeChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_type', models.CharField(choices=[('manual', 'Ручная регистрация'), ('api', 'API'), ('ai', 'ИИ-обработка обращений'), ('1c', '1С:ЖКХ')], max_length=16)),
                ('description', models.TextField(blank=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('residential_complex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intake_channels', to='complexes.residentialcomplex')),
            ],
            options={
                'ordering': ('channel_type',),
                'constraints': [models.UniqueConstraint(fields=('residential_complex', 'channel_type'), name='unique_intake_channel_per_complex')],
            },
        ),
        migrations.CreateModel(
            name='ResidentialComplexService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_priority', models.CharField(choices=[('low', 'Низкий'), ('normal', 'Обычный'), ('high', 'Высокий'), ('urgent', 'Срочный')], default='normal', max_length=16)),
                ('response_time_minutes', models.PositiveIntegerField(default=1440)),
                ('working_hours', models.CharField(default='Круглосуточно', max_length=100)),
                ('auto_assignment_enabled', models.BooleanField(default=True)),
                ('fallback', models.CharField(choices=[('dispatcher', 'Передать диспетчеру'), ('hold', 'Оставить без назначения')], default='dispatcher', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='complex_settings', to='providers.servicecategory')),
                ('residential_complex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_settings', to='complexes.residentialcomplex')),
            ],
            options={
                'ordering': ('category__name',),
                'constraints': [models.UniqueConstraint(fields=('residential_complex', 'category'), name='unique_service_setting_per_complex')],
            },
        ),
    ]
