# Generated by Django 5.2.15 on 2026-07-20 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complexes', '0004_residentialcomplex_contact_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResidentialComplexNotificationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('new', 'Поступила новая заявка'), ('unassigned', 'Заявка осталась без назначения'), ('overdue', 'Нарушен срок реакции'), ('completed', 'Заявка завершена')], max_length=24)),
                ('recipient', models.CharField(choices=[('dispatchers', 'Диспетчеры ЖК'), ('managers', 'Руководители ЖК'), ('provider_managers', 'Руководитель поставщика')], max_length=24)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('residential_complex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_rules', to='complexes.residentialcomplex')),
            ],
            options={
                'ordering': ('event', 'recipient'),
                'constraints': [models.UniqueConstraint(fields=('residential_complex', 'event', 'recipient'), name='unique_notification_rule_per_complex')],
            },
        ),
    ]
