# Generated by Django 5.2.15 on 2026-07-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providermembership',
            name='role',
            field=models.CharField(choices=[('manager', 'Руководитель поставщика'), ('employee', 'Исполнитель')], max_length=20),
        ),
    ]
