# Generated by Django 5.2.15 on 2026-08-12 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complexes', '0005_residentialcomplexnotificationrule'),
        ('providers', '0002_alter_providermembership_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_minutes', models.PositiveIntegerField(default=120)),
                ('capacity_per_slot', models.PositiveIntegerField(default=1)),
                ('available_weekdays', models.JSONField(default=list)),
                ('available_from', models.TimeField()),
                ('available_until', models.TimeField()),
                ('minimum_lead_hours', models.PositiveIntegerField(default=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offerings', to='providers.servicecategory')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_offerings', to='providers.provider')),
                ('residential_complex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_offerings', to='complexes.residentialcomplex')),
            ],
            options={
                'ordering': ('category__name', 'price', 'title'),
                'constraints': [models.UniqueConstraint(fields=('residential_complex', 'provider', 'category'), name='unique_provider_offering_per_complex_category'), models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='service_offering_price_not_negative')],
            },
        ),
    ]
