# Generated by Django 5.2.15 on 2026-08-12 10:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resident_portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='published_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
