# Generated by Django 5.2.15 on 2026-08-12 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0003_serviceoffering'),
        ('resident_portal', '0002_alter_newspost_published_at'),
        ('tickets', '0006_applicant_user_ticket_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField()),
                ('scheduled_start', models.TimeField()),
                ('scheduled_end', models.TimeField()),
                ('quoted_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='RUB', max_length=3)),
                ('resident_comment', models.TextField(blank=True)),
                ('resident_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='providers.serviceoffering')),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_order', to='tickets.ticket')),
            ],
            options={
                'ordering': ('-scheduled_date', '-scheduled_start'),
                'constraints': [models.CheckConstraint(condition=models.Q(('quoted_price__gte', 0)), name='service_order_price_not_negative')],
            },
        ),
    ]
